apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontenddeployment
  name: frontenddeployment
spec:
  replicas: {{.Values.frontendReplicas}}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: sunishsurendrank/frontend:{{.Values.frontendTag}}
        name: frontend
        ports:
        - containerPort: 80

