apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontendnodeport
  name: frontendnodeport
spec:
  ports:
  - name: 80-80
    nodePort: 30001
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
  type: NodePort

