apiVersion: v1
kind: Service
metadata:
  labels:
    app: gonodeport
  name: gonodeport
spec:
  ports:
  - name: 30003-9090
    nodePort: 30003
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    app: gowebservice
  type: NodePort

